# Generated by Django 4.1.7 on 2023-04-12 19:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_quiz_fail_text_quiz_success_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="fail_text",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="success_text",
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="при желании прикрепите картинку",
                        upload_to="quiz_results/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpeg", "jpg", "png", "mp4"]
                            )
                        ],
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="этот текст может отличаться в зависимости от кол-ва правильных ответов",
                        verbose_name="Текст результата.",
                    ),
                ),
                (
                    "correct_answer_cnt",
                    models.IntegerField(
                        help_text="при достижении определенного количества определеяет текст результата",
                        verbose_name="Необходимое кол-во правильных ответов.",
                    ),
                ),
                (
                    "quiz_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quiz.quiz"
                    ),
                ),
            ],
        ),
    ]
