version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: drf_sobitie_local
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./drf_sobitie/static:/app/drf_sobitie/static
      - ./drf_sobitie/db:/app/drf_sobitie/db
      - ./drf_sobitie:/app/drf_sobitie
    env_file:
      - ./.env
    ports:
      - "8000:8000"
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: bot_sobitie_local
    restart: always
    command: sh -c "python manage.py runbot"
    volumes:
      - ./drf_sobitie/media:/app/drf_sobitie/media
      - ./drf_sobitie:/app/drf_sobitie
    depends_on:
      - web
    environment:
      - API_ADDRESS=http://web:8000
    env_file:
      - ./.env
  scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: scheduler_sobitie_local
    restart: always
    command: sh -c "python manage.py start-scheduler"
    depends_on:
      - web
    volumes:
      - ./drf_sobitie:/app/drf_sobitie
    env_file:
      - ./.env
    environment:
      - API_ADDRESS=http://web:8000
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./nginx/nginx_local.conf:/etc/nginx/conf.d/default.conf # не грузить статику админки
      - ./drf_sobitie/static:/var/html/static
      - ./drf_sobitie/media:/var/html/media
    depends_on:
      - web
volumes:
  static_value:
  media_value:
  data:
