version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf_sobitie
    restart: always
    command: python drf_sobitie/manage.py runserver 0:8000
    volumes:
      - static_value:/app/drf_sobitie/static/  
    env_file:
      - ./.env
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_sobitie
    restart: always
    command: python src/main.py
    volumes:
      - media_value:/app/src/media/
    depends_on:
      - web
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value: