version: '3.8'

services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - db_value:/var/lib/postgresql/data/
  web:
    image: mnmyasis/sobitie:latest
    container_name: drf_sobitie
    restart: always
    command: sh -c "cd drf_sobitie/; gunicorn drf_sobitie.wsgi:application --bind 0:8000"
    volumes:
      - static_value:/app/drf_sobitie/static/
      - data:/app/drf_sobitie/db
    env_file:
      - ./.env
  bot:
    image: mnmyasis/sobitie:latest
    container_name: bot_sobitie
    restart: always
    command: sh -c "cd drf_sobitie; python manage.py runbot"
    volumes:
      - media_value:/app/src/media/
    depends_on:
      - web
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  db_value:
  static_value:
  media_value:
  data: