version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: drf_sobitie
    restart: always
    command: bash -c "python drf_sobitie/manage.py migrate && python drf_sobitie/manage.py runserver"     
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_sobitie
    restart: always
    command: python src/main.py
    depends_on:
      - web
    env_file:
      - ./.env
