# Generated by Django 4.1.7 on 2023-05-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stickerpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='введите название стикерпака', max_length=50, unique=True, verbose_name='Название стикерпака')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Превью')),
                ('description', models.TextField(blank=True, help_text='Опишите стикерпак', verbose_name='Описание стикер-пака')),
                ('url_sticker', models.URLField(help_text='Вставьте ссылку на стикерпак', unique=True, verbose_name='Ссылка на стикер-пак')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Стикер-пак',
                'verbose_name_plural': 'Стикер-паки',
                'db_table': 'Stickerpack',
            },
        ),
    ]
