# Константы состояний
START_STATE = 'START_STATE'
SUPPORT_STATE = 'SUPPORT_STATE'
ABOUT_US_STATE = 'ABOUT_US_STATE'
DONATION_OPTIONS_STATE = 'DONATION_OPTIONS_STATE'


# Константы стратового меню
ABOUT_US = 'ABOUT_US'
END = 'END'
EVENTS = 'EVENTS'
GIVE_SUPPORT = 'GIVE_SUPPORT'
INTERACTIVE_GAME = 'INTERACTIVE_GAME'


# Константы для меню "Мероприятия"
CHOOSE_EVENT = 'CHOOSE_EVENT'
GET_MASTER_CLASS = 'GET_MASTER_CLASS'
GET_PERFORMANCES = 'GET_PERFORMANCES'
GET_EVENT = 'GET_EVENT'


# Константы для меню "Помочь"
ATTEND_EVENT = 'ATTEND_EVENT'
OUR_NEEDS = 'OUR_NEEDS'
SHOW_DONATION_OPTIONS = 'SHOW_DONATION_OPTIONS'
PARTNERSHIP = 'PARTNERSHIP'
ORDER_SOUVENIRS = 'ORDER_SOUVENIRS'
BECOME_SPONSOR = 'BECOME_SPONSOR'
BECOME_VOLUNTEER = 'BECOME_VOLUNTEER'
FOLLOW_US = 'FOLLOW_US'
RETURN_TO_PREVIOUS = 'RETURN_TO_PREVIOUS'

# Константы для подменю "Выбрать способ пожертвования"
DONATE_WITH_SITE_FORM = 'DONATE_WITH_SITE_FORM'
DONATE_WITH_VK = 'DONATE_WITH_VK'
DONATE_WITH_TINKOFF = 'DONATE_WITH_TINKOFF'
DONATE_THROUGH_CHARITY_FUND = 'DONATE_THROUGH_CHARITY_FUND'
RETURN_TO_HELP_MENU = 'RETURN_TO_HELP_MENU'


# Константы для меню "О нас"
CONTACTS = 'CONTACTS'
LEGAL_DOCUMENTS = 'LEGAL_DOCUMENTS'
REPORTS = 'REPORTS'
PROJECTS = 'PROJECTS'





