# Константы состояний
START_STATE = 'START_STATE'
SUPPORT_STATE = 'SUPPORT_STATE'
ABOUT_US_STATE = 'ABOUT_US_STATE'
DONATION_OPTIONS_STATE = 'DONATION_OPTIONS_STATE'
SUPPORT_FOLLOW_STATE = 'SUPPORT_FOLLOW_STATE'
ORDER_SOUVENIR_STATE = 'ORDER_SOUVENIR_STATE'
