# Generated by Django 4.1.7 on 2023-03-15 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_quote_alter_event_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
