# Generated by Django 4.1.7 on 2023-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.BigIntegerField(
                        editable=False, unique=True, verbose_name="id"
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "Событие", "verbose_name_plural": "События"},
        ),
    ]
