name: Check code style

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install pipx
          pipx install poetry

      - name: Validate and install dependencies with Poetry
        run: |
          poetry check
          poetry lock --check
          poetry install

      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Check import formatting with isort
        run: |
          poetry run isort . --check-only --diff
