name: CI/CD sobitie
run-name: ${{ github.actor }} CI/CD process...
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VKAREV_SERVER }}
          username: ${{ secrets.VKAREV_USER }}
          port: ${{ secrets.VKAREV_PORT }}
          key: ${{ secrets.VKAREV_KEY }}
          script: |
            cd sobitie
            echo DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}" >> DOCKER_PASSWORD
            echo DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}" >> DOCKER_USERNAME
            echo TELEGRAM_TOKEN="${{ secrets.TELEGRAM_TOKEN }}" >> TELEGRAM_TOKEN
            echo ${{ secrets.SSH_KEY }} >> SSH_KEY
            echo DJ_SECRET_KEY="${{ secrets.DJ_SECRET_KEY }}" >> .env
            echo VK_SERVICE_KEY="${{ secrets.VK_SERVICE_KEY }}" >> .env
            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
            echo EVENTS_URL=${{ secrets.EVENTS_URL }} >> .env
            echo QUOTE_URL=${{ secrets.QUOTE_URL }} >> .env
            echo QUIZZES_URL=${{ secrets.QUIZZES_URL }} >> .env
            echo STICKERPACK_URL=${{ secrets.STICKERPACK_URL }} >> .env
            echo NOTIFICATIONS_API_URL=${{ secrets.NOTIFICATIONS_API_URL }} >> .env
            echo CHECK_FOR_SUBSCRIPTION_API_URL=${{ secrets.CHECK_FOR_SUBSCRIPTION_API_URL }} >> .env
            echo SEND_EVENT_NOTIFICATION_URL=${{ secrets.SEND_EVENT_NOTIFICATION_URL }} >> .env
            echo "OK"
